apiVersion: v1
kind: ReplicationController
metadata:
  name: phpweb
  namespace: scpman
  labels:
    name: phpweb
spec:
  replicas: 3 
  selector:
    name: phpweb
  template:
    metadata:
      labels:
        name: phpweb
    spec:
      containers:
      - name: phpweb
        image: 192.168.1.11:5000/nginx-php:7.0-composer-k8s
        env:
        - name: GET_HOSTS_FROM
          value: env
        ports:
        - containerPort: 80
