apiVersion: v1
kind: ServiceAccount
metadata:
  name: traefik-ingress2
  namespace: gocluster
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: traefik-ingress2
subjects:
  - kind: ServiceAccount
    name: traefik-ingress2
    namespace: gocluster
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

